### ISSUE TITLE
Duping Bug - Shulker

### ISSUE THREAD

**Issue by Serial1990** [Avankziar/ShopALotExtra#1]
SALE  1-0-29
Paper-220 1.19.2

Erklärung:

1. Shulker individuell befüllen. (So das auf jeden Slot ein Item liegt.)
2. Shop erstellen und die Shulker für den Shop registrieren
3. Eine Leere Shulker der gleichen Farbe im Shop hinzufügen
4. die Shulker wieder entnehmen, somit ist die leere Shulker die individuell befüllte Shulker von Anfang.

Somit kann man jedes Item beliebig oft in einer Shulker duplizieren.

**Comment by Serial1990** [comment]
Alternativer Vorschlag, individuell gefüllte Shulker einfach gänzlich entfernen.

**Comment by Avankziar** [comment]
Ist umgesetzt im Update 1-1-0
