### ISSUE TITLE
DefaultStartItemStorage greift nicht

### ISSUE THREAD

**Issue by Serial1990** [Avankziar/ShopALotExtra#2]
SALE 1-0-30
Paper-307 1.19.2

Erklärung:

Das ändern der Einstellung von DefaultStartItemStorage zeigt keine Auswirkung.

Es wurde von 3456 auf 6912 geändert und nach einen Neustart wurden neu erstellte Schilder weiterhin mit 3456 ItemSlots erstellt.

**Comment by Avankziar** [comment]
Ist für die nächste Version (vorraussichtlich 1-1-0) gefixt.
