### ISSUE TITLE
Shopnamen

### ISSUE THREAD

**Issue by Blockdigga** [Avankziar/ShopALotExtra#3]
Kann man in dem Sale Plugin das so ändern das der Shopname ( den man ja ändern kann . Also anstatt einer Nr. einen Namen) automatisch von dem Item übernommen wird welches man da reinlegt ? 
zB. mach ich einen Shop mit Fichtenholz oder Cobble soll der Shopname dann Cobblestone oder Fichtenholz heißen. Ich weis das man das alles manuell eingeben kann. Aber bei vielen Schildern ist das schon mühselig  

So sieht man dann auch gleich anstatt "Shop 6351 ist leer , Shop Cobblestone ist leer " und muss nicht erst lange suchen 

Ich weis das das mit manchen Items vilt nicht gehen wird. aber bei den Standartitems sollte das doch machbar sein ,oder ?

**Comment by Avankziar** [comment]
Also wenn das Item Cobble ist, soll der Shopname Cobble sein.
Wie steht es denn mit benannten Items? Bspw. bei einem Cobble Item mit dem Namen "&cSuper Stein"? Denn eigentlich sind Leerzeichen nicht erlaubt. Klar die kann man zu _ machen. Oder benannte Items werden ignoriert, geht auch^^

**Comment by Blockdigga** [comment]
benannte Items werden ignoriert. Geht ja nur um die Standartitems.
Das würde halt das drüber hovern im Chat ersparen :) Gerade wenn ich irgendwas am machen bin. Bei ner Meldung geht der Chat ja kurz auf und ich würde gleich sehen was da vilt im Shop nicht mehr vorhanden ist.
Es is halt nur so ne Idee

**Comment by Avankziar** [comment]
Gut, wird so übernommen.

**Comment by Avankziar** [comment]
Ist umgesetzt, und wird in dem nächsten Update enthalten sein.
