### ISSUE TITLE
SQLException! Could not get a ShopAccessType Object!

### ISSUE THREAD

**Issue by Serial1990** [Avankziar/ShopALotExtra#4]
SaLe Version: 1-1-0
Paper Version: 1.19.2 #307

Log Warn: [https://pastebin.com/JHcV72RS](url)

**Comment by Avankziar** [comment]
Fehler kann nur ein von 2 sein:
- Korrupte Daten
- Laufzeitproblem.

Daher abgelehnt, bis weitere Daten vorliegen.
