### ISSUE TITLE
Money Log Spam

### ISSUE THREAD

**Issue by Serial1990** [Avankziar/ShopALotExtra#5]
SaLe Version: 1-1-0
Paper Version: 1.19.2 #307

Erklärung:

Wenn man ein volles Inventar hat und bei anderen Spielern etwas über den Shop kaufen will, wird der Log vom Verkäufer zugespamt.

![Money](https://user-images.githubusercontent.com/1337501/231228666-e16242b0-aec3-4df4-86b3-2c4b84f46e40.PNG)

**Comment by Avankziar** [comment]
Gefixt. Wird im nächsten Updaten enthalten sein.
