### ISSUE TITLE
Item Löschung bei Shopbefüllung in der GUI

### ISSUE THREAD

**Issue by Serial1990** [Avankziar/ShopALotExtra#6]
SaLe Version: 1-2-0
Paper Version: 1.19.2 #307

Erklärung:

Füllt man einen Shop bis zu einen Stand **weniger als ein Stack** und öffnet den Shop um das Item hinzuzufügen, wird der ganze Stack, sofern man ihn ausgewählt hat eingefügt.

Das heißt, hat man als Beispiel man hat 3455 / 3456 Items im Shop und fügt ein Stack des Items hinzu, werden 63 der Items einfach gelöscht.

**Comment by Avankziar** [comment]
Gefixt. Im nächsten Update enthalten.
